<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="SkiaSharp" Version="4.151.2" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux" Version="4.151.2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../NexusManager.Actions/NexusManager.Actions.csproj" />
    <ProjectReference Include="../NexusManager.Audio/NexusManager.Audio.csproj" />
    <ProjectReference Include="../NexusManager.Device/NexusManager.Device.csproj" />
    <ProjectReference Include="..\NexusManager.Sensors\NexusManager.Sensors.csproj" />
  </ItemGroup>
</Project>
